server:
  server:
  port: ${PORT:8167}

spring:
  application:
    name: ate-management-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
      org.springframework: WARN 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL:192.168.200.67:3306}/history?autoreconnect=true;noAccessToProcedureBodies=true;useSSL=false       
    username: ${DB_USERNAME:iotadmin}
    password: ${DB_PASSWORD:Dbst@321}  
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa: 
    show-sql: true
    hibernate:
       ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
       
     
  
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    MaxAutoRetries: 3 
    MaxAutoRetriesNextServer: 1 
    ReadTimeout: 1000 
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
coreAPI:
  url: ${CORE_URL:http://192.168.200.67:8161/iot/core/api/v1}
  username: ${CORE_USER:duadmin}
  password: ${CORE_PASS:IoT3st@123}
  
max:
 read:
  attempts: 2
